server:
  port: 9000

spring:
  jackson:
    serialization:
      indent_output: true

  datasource:
    url: jdbc:postgresql://localhost:5432/Avito
    username: developer
    password: java

#  jpa:
#    hibernate:
#      ddl-auto: create